//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIENBANVIPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIENBANVIPHAM()
        {
            this.CUONSACHes = new HashSet<CUONSACH>();
        }
    
        public string MaViPham { get; set; }
        public string MaDocGia { get; set; }
        public string MaNhanVien { get; set; }
        public string LyDo { get; set; }
        public Nullable<long> TienPhat { get; set; }
        public string TinhTrangSach { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUONSACH> CUONSACHes { get; set; }
    }
}
