//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAUSACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAUSACH()
        {
            this.CUONSACHes = new HashSet<CUONSACH>();
            this.THONGTINNHAPSACHes = new HashSet<THONGTINNHAPSACH>();
            this.TACGIAs = new HashSet<TACGIA>();
            this.NHAXUATBANs = new HashSet<NHAXUATBAN>();
        }
    
        public string MaDauSach { get; set; }
        public string TenDauSach { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> LanTaiBan { get; set; }
        public string NamXuatBan { get; set; }
        public long GiaTien { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public string MoTa { get; set; }
        public string TheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUONSACH> CUONSACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINNHAPSACH> THONGTINNHAPSACHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACGIA> TACGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHAXUATBAN> NHAXUATBANs { get; set; }
    }
}
