//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUONTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUMUONTRA()
        {
            this.THONGTINMUONTRAs = new HashSet<THONGTINMUONTRA>();
        }
    
        public string MaMuonTra { get; set; }
        public string MaDocGia { get; set; }
        public string MaNhanVien { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime HanTra { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGTINMUONTRA> THONGTINMUONTRAs { get; set; }
    }
}
