//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINMUONTRA
    {
        public string MaMuonTra { get; set; }
        public string MaSach { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual PHIEUMUONTRA PHIEUMUONTRA { get; set; }
    }
}
